apiVersion: v1
kind: Service
metadata:
  name: mockapi-service
spec:
  type: NodePort
  selector:
    app: mockapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081