apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
      - name: shopping-frontend
        image: shopping-frontend:latest
        ports:
        - containerPort: 80
