apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend-service
spec:
  selector:
    app: shopping-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
